In [1]:
#!pip show numpy
#!pip install keras==2.9.0 
#!pip install protobuf
import pandas as pd
import numpy as np
import nltk
#nltk.download('wordnet')
#nltk.download('stopwords')



[notice] A new release of pip is available: 24.2 -> 25.0
[notice] To update, run: pip install --upgrade pip


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from numpy import loadtxt
from nltk.corpus import stopwords
stop = stopwords.words('english')
import csv

#Lade den Inhalt der gelabelten CSV-Datei mit den Kommentaren und den label (0=negativ, 1=positiv, 2=neutral)
content = pd.read_csv('youtube_comments_complete.csv', sep='#', on_bad_lines='skip', engine='python')

#Filtere den Kommentar mit den meisten Wörtern raus und gebe ihn aus
print("Measuring the comment with the most words...")
max_comment = max(content['reviewText'], key=len)
print(max_comment)

#Zähle die Anzahl der Wörter von dem größten Kommentar
print("Biggest comment has number of words:")
max_comment_char_count = int(len(max_comment))
print(max_comment_char_count)

#Gebe mir die Anzahl der Zeilen der geladenen CSV aus
print("CSV has this many lines..")
print(len(content))

#Trenne den Datensatz in Trainingsdaten und Testdaten auf
print("Train data..")
train_data = content[:472] #nur die ersten X Zeilen laden
print(train_data)

#Gebe die Test und Trainingsdaten aus
print("Test data..")
test_data = content[-472:] #nur die letzten X Zeilen laden
print(test_data)

Measuring the comment with the most words...
first of all batman and joker were both criminals meaning the real people meaning the three main joker including the pop 80s 90s joker that has just been declared brain dead from guilt syndrome. batman also known as bruce wayne or wayne lauwrance aka victor von terrible died in the 2008 era of west nile capsia virus in jail for mass murder. the joker of the 80s was once bruces kidnap victim but took to a pop image of villainy when he escaped the actually wayne manor thought to be in gotham but which is actual in north of newark nj. gotham is a small island in between staten island and the nj coast thought of as part of new york nyc foot clan and marshal law district because the kids are tough because of mutants etc. muir of 400 miles approx off long island sound, and metropolis is now a governement island state for only the super rich and powerful closed off but considered one of the real 59 states as thats how many there really are. muir is

In [3]:
#Aufteilen des Trainingsdatensatz in die Spalten für den Kommentar('reviewText') und
#den labels('labelPos') und geben diese aus
train_y = train_data['reviewText']
print(train_y)
train_x = train_data['labelPos']
print(train_x)

#Mache das gleiche für die Testdaten
test_y = test_data['reviewText']
print(test_y)
test_x = test_data['labelPos']
print(test_x)

print("Train-Data")
print(train_data)

0      this movie sucked so bad they had to stan him ...
1      better name this movie as musical clown. bigge...
2      batman gonna laugh too much seeing this joker....
3      wtf. who the director is. fckng idiot spoiled ...
4      whatever they do but cant do it like heath led...
                             ...                        
467    what hell v the zombie land is real black ops2...
468           first one tge mind chip they went up hevan
469            weather stared monkey pod and conor vuris
470    not broken up fat boy and wearing pink thing h...
471    its scary that this rubbish isnt the low point...
Name: reviewText, Length: 472, dtype: object
0      0
1      0
2      0
3      0
4      2
      ..
467    2
468    2
469    2
470    0
471    0
Name: labelPos, Length: 472, dtype: int64
469            weather stared monkey pod and conor vuris
470    not broken up fat boy and wearing pink thing h...
471    its scary that this rubbish isnt the low point...
472           yo

In [4]:
#Gebe mir die Anzahl der Zeilen in den Test- und Trainingsdaten
print(len(test_x))
print(len(test_y))

472
472


In [5]:
#Erstelle Vokabular
#Limitiere die maximale Anzahl an Wörtern im Vokabular
num_words = 1000

#Setze den Token der verwendet werden soll, wenn das Wort nicht im
#Vokabular vorkommt
oov_token = '<UNK>'

#Setze das Padding und Trunc auf Post, sodass die Vektoren am Ende mit Nullen aufgefüllt
#und abgeschnitten werden
pad_type = 'post'
trunc_type = 'post'

In [6]:
#Erstelle den Tokenizer
tokenizer = Tokenizer(num_words=num_words, oov_token=oov_token)
tokenizer.fit_on_texts(train_y)

#Erstelle einen Wörter-Index
word_index = tokenizer.word_index

#Kodierung der Trainingsdaten und Testdaten
train_sequences = tokenizer.texts_to_sequences(train_y)
test_sequences = tokenizer.texts_to_sequences(test_y)

#Gib die maximale Länge der Trainings- und Testsequenzen aus
maxlen = max([len(x) for x in train_sequences])
print(maxlen)
maxlen2 = max([len(x) for x in test_sequences])
print(maxlen2)


#Padding der Trainings- und Testsequenzen
train_padded = pad_sequences(train_sequences, padding=pad_type, truncating=trunc_type, maxlen=maxlen)
test_padded = pad_sequences(test_sequences, padding=pad_type, truncating=trunc_type, maxlen=maxlen)

#Länge der padded Trainings- und Testdaten
print(max([len(x) for x in train_padded]))
print(max([len(x) for x in test_padded]))

#Gebe den Word-Index aus
#Hier werden die Token als Wort-Wertepaare gespeichert
print(word_index)

#Lade den PorterStemmer um aus den Wörtern den Wortstamm zu machen
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()
word_index = [stemmer.stem(word) for word in word_index]

#Gib die Stammwörter aus
print(word_index)

179
269
179
179
{'<UNK>': 1, 'the': 2, 'a': 3, 'i': 4, 'and': 5, 'to': 6, 'is': 7, 'this': 8, 'it': 9, 'in': 10, 'movie': 11, 'of': 12, 'that': 13, 'br': 14, 'for': 15, 'was': 16, 'one': 17, 'like': 18, 'be': 19, 'they': 20, 'so': 21, 'season': 22, 'but': 23, '2': 24, 'not': 25, 'my': 26, 'game': 27, 'you': 28, 'just': 29, 'what': 30, 'he': 31, 'with': 32, 'joker': 33, 'first': 34, 'its': 35, 'good': 36, 'will': 37, 'on': 38, 'if': 39, 'are': 40, 'as': 41, 'mission': 42, 'all': 43, 'why': 44, 'me': 45, 'href': 46, 'uckszu2wh9gy1mb0dv': 47, '11ujg': 48, 'fgfy9digyjbhghlzodidw': 49, 'impossible': 50, 'who': 51, 'im': 52, 'watch': 53, 'gonna': 54, '1': 55, 'film': 56, 'trailer': 57, 'more': 58, 'tom': 59, 'would': 60, 'out': 61, 'have': 62, 'from': 63, 'squid': 64, 'games': 65, 'no': 66, 'up': 67, 'reckoning': 68, 'do': 69, 'watching': 70, 'again': 71, 'see': 72, 'wait': 73, 'really': 74, 'character': 75, 'musical': 76, 'dead': 77, 'cant': 78, 'can': 79, 'how': 80, 'best': 81, 'people': 8

In [7]:
#Funktion um aus den Sequenzen Vektoren zu machen
def vectorize(sequences, dimension = int(max_comment_char_count)): #Dimension bezieht sich auf die maximale Größe des längsten Kommentars
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1
    return results

#Rufe die Funktion aus, um die Trainingsdaten- und Labels zu einem Vektor umzuwandeln
train_x = vectorize(train_x).astype("int64")
train_y = np.array(train_padded).astype("float64")

test_x = vectorize(test_x).astype("int64")
test_y = np.array(test_padded).astype("float64")

#Gebe mir die Trainings- und Testdaten aus
print("Testdata:Y(Comments)")
print(test_y)
print("Testdata:X(Labels)")
print(test_x)

Testdata:Y(Comments)
[[  1.   1.   1. ...   0.   0.   0.]
 [ 25.   1.  67. ...   0.   0.   0.]
 [ 35. 613.  13. ...   0.   0.   0.]
 ...
 [133. 639.  36. ...   0.   0.   0.]
 [ 16.  54. 150. ...   0.   0.   0.]
 [ 16.  74.   1. ...   0.   0.   0.]]
Testdata:X(Labels)
[[0 0 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]]


In [8]:
#Gebe den Wörter-Index, die Trainingssequenz und deren Padded Version, sowie deren Form und die Datentypen aus
print("Word index:\n", word_index)
print("Training sequences:\n", train_sequences)
print("Padded training sequences:\n", train_padded)
print("Padded training shape:", train_padded.shape)
print("Training sequences data type:", type(train_sequences))
print("Padded Training sequences data type:", type(train_padded))

Word index:
 ['<unk>', 'the', 'a', 'i', 'and', 'to', 'is', 'thi', 'it', 'in', 'movi', 'of', 'that', 'br', 'for', 'wa', 'one', 'like', 'be', 'they', 'so', 'season', 'but', '2', 'not', 'my', 'game', 'you', 'just', 'what', 'he', 'with', 'joker', 'first', 'it', 'good', 'will', 'on', 'if', 'are', 'as', 'mission', 'all', 'whi', 'me', 'href', 'uckszu2wh9gy1mb0dv', '11ujg', 'fgfy9digyjbhghlzodidw', 'imposs', 'who', 'im', 'watch', 'gonna', '1', 'film', 'trailer', 'more', 'tom', 'would', 'out', 'have', 'from', 'squid', 'game', 'no', 'up', 'reckon', 'do', 'watch', 'again', 'see', 'wait', 'realli', 'charact', 'music', 'dead', 'cant', 'can', 'how', 'best', 'peopl', 'ever', 'part', 'we', 'now', 'after', 'better', 'make', 'watch', 'gt', 'bad', 'go', 'by', 'did', 'also', 'becaus', 'or', 'know', 'when', 'back', 'real', 'cruis', 'man', 'ladi', 'an', 'think', 'veri', 'still', 'anoth', 'than', 'super', 'had', 'too', 'look', 'gaga', 'there', 'then', 'get', 'ha', 'time', 'dont', 'hi', 'never', 'year', 'that

In [9]:
#Erstelle aus den Testdaten ebenfalls die Sequenz und die padded Sequenz
test_sequences = tokenizer.texts_to_sequences(test_data['reviewText'])
test_padded = pad_sequences(test_sequences, padding=pad_type, truncating=trunc_type, maxlen=maxlen)

In [10]:
#Gebe die Testseqzenz-, Padded und die Form aus
print("Testing sequences:\n", test_sequences)
print("\nPadded testing sequences:\n", test_padded)
print("\nPadded testing shape:",test_padded.shape)

Testing sequences:
 [[1, 1, 1, 1, 5, 635, 1], [25, 1, 67, 1, 638, 5, 1, 562, 250, 1, 163, 1, 163, 1], [35, 613, 13, 8, 399, 457, 2, 314, 1, 15, 326], [28, 79, 1, 2, 1, 10, 258, 98, 1, 17], [8, 57, 16, 1, 3, 494, 2, 11, 238, 1], [81, 57, 92, 11], [189, 57], [326, 2, 1, 172, 11, 37, 1, 82, 1, 14, 1, 282, 1, 763, 9, 132, 1, 1, 282], [4, 501, 100, 2, 1, 16, 1], [30, 4, 37, 298, 7, 418, 2, 56, 159, 41, 9, 7, 9, 7, 3, 108, 169, 924, 57], [8, 7, 25, 93, 6, 150, 2, 192, 28, 107, 168, 1, 532, 1, 272, 1, 1, 6, 123, 1], [2, 1, 8, 11, 1, 113, 101, 118], [1, 15, 133, 166, 2, 1, 12, 562, 98, 543], [66, 1, 205, 10, 1, 1], [115, 52, 74, 25, 54, 1, 23, 4, 107, 8, 57, 7, 108, 613, 15, 43, 1], [8, 11, 16, 293, 305, 23, 301, 66, 1, 13, 2, 57, 16, 1], [2, 293, 197, 139, 224, 11, 4, 402, 321, 2, 102, 710, 44, 82, 18, 9], [66, 1], [8, 57, 113, 45, 1, 8, 16, 54, 19, 2, 1, 139, 224, 56, 12, 43, 121, 104, 4, 16, 21, 194], [4, 1, 1, 13, 155, 1, 702, 58, 10, 2, 56], [543, 1, 7, 102, 1, 543, 250, 10, 1, 1, 388], [

In [11]:
#Importiere notwendige Bibliotheken aus Keras für das Neuronale Netz
import numpy as np
import tensorflow.keras as keras
from tensorflow.keras.utils import to_categorical
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import models

In [12]:
#Erstelle ein Sequentielles Modell
model = models.Sequential()

2025-01-31 22:32:49.770129: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [13]:
#Füge Layer zu dem Modell hinzu
#Füge den Input Layer mit der Aktivierungsfunktion relu hinzu und füge den Netzwerk-Layer mit 64 hinzu
#Er gibt den Input des Layers an die Neuronen weiter
#Die relu-Funktion: ist eine gleichgerichtete Lineareinheit, wenn der negativ ist, wird dieser zu einer 0
#Dieser Schwellenwert lässt sich einsetellen, positive Werte werden nicht geändert
model.add(layers.Dense(69, activation = "relu", input_shape=(2, int(max_comment_char_count)))) ##jetzt in der selben shape, je nach längstem Kommentar
#Erstelle die Hidden Layer
#Dropout setzt zufällig Eingabeeinheiten auf 0, um ein Overfitting zu verhindern
#Bei der Aktivierungsfunktion linear ist die Aktivierung proportional zum entsprechenden Input
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(23, activation = "linear"))
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(23, activation = "linear"))
model.add(layers.Dropout(0.3, noise_shape=None, seed=None))
model.add(layers.Dense(23, activation = "relu"))
#Ausgabelayer
model.add(layers.Dense(1, activation = "linear"))
#Gebe mir den Aufbau des Modells aus
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2, 69)             101361    
_________________________________________________________________
dropout (Dropout)            (None, 2, 69)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 2, 23)             1610      
_________________________________________________________________
dropout_1 (Dropout)          (None, 2, 23)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 2, 23)             552       
_________________________________________________________________
dropout_2 (Dropout)          (None, 2, 23)             0         
_________________________________________________________________
dense_3 (Dense)              (None, 2, 23)             5

In [14]:
#Erstelle das Model und setze Flags für den optimizer (adam für spärliche features in einem Modell, als
#vorhersage, loss-Funktion: hier berechnet es die Kreuzentropie
#zwischen vorhergesagten Klassen und den richtigen Klassen und die Metrik zum messen der Genauigkeit
model.compile(
optimizer = "ftrl",
loss = "binary_crossentropy",
metrics = ["accuracy"]
)

In [15]:
#Ausgeben der Form der Trainind- und Testdaten und Labels
print("Traindata shape..")
print(len(train_x))
print(len(train_y))

print("Testdata shape..")
print(len(test_x))
print(len(test_y))

Traindata shape..
472
472
Testdata shape..
472
472


In [16]:
#Trainiere das Modell in den vorgegebenen Epochen, mit der entsprechend großen Batch Größe und den hier gegebenen
#Validation Split. Gebe die Trainingsdaten/Labels, sowie die Testdaten/Labels.
#Shuffle wird den gesamten Datensatz durcheinanderwürfeln, bevor die Batches erstellt werden
results = model.fit(
train_x, train_y,
epochs= 10,
batch_size = 100,
validation_split=0.1, 
shuffle=True,
validation_data = (test_x, test_y)
)

Epoch 1/10


2025-01-31 22:32:49.843448: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
2025-01-31 22:32:49.843714: I tensorflow/core/platform/profile_utils/cpu_utils.cc:114] CPU Frequency: 24000000 Hz


5/5 [==============================] - 0s 18ms/step - loss: 71.1448 - accuracy: 0.8277 - val_loss: 9.6684 - val_accuracy: 0.6366
Epoch 2/10
5/5 [==============================] - 0s 4ms/step - loss: 86.2173 - accuracy: 0.9181 - val_loss: 5.1298 - val_accuracy: 0.6398
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 36.2707 - accuracy: 0.5932 - val_loss: -42.3510 - val_accuracy: 0.2671
Epoch 4/10
5/5 [==============================] - 0s 4ms/step - loss: -29.5734 - accuracy: 0.4630 - val_loss: 43.8195 - val_accuracy: 0.9330
Epoch 5/10
5/5 [==============================] - 0s 4ms/step - loss: -12.4044 - accuracy: 0.3343 - val_loss: 16.0442 - val_accuracy: 0.8369
Epoch 6/10
5/5 [==============================] - 0s 4ms/step - loss: 44.4943 - accuracy: 0.8725 - val_loss: 37.1228 - val_accuracy: 0.9517
Epoch 7/10
5/5 [==============================] - 0s 4ms/step - loss: 61.9907 - accuracy: 0.8913 - val_loss: 58.0460 - val_accuracy: 0.9517
Epoch 8/10
5/5 [=============

In [17]:
#Berechnen der Genauigkeit mit zwei Nachkommastellen
#Die Verbose-Einstellung zeigt den Trainingsprozess
scores = model.evaluate(test_x, test_y, verbose=1)
print("Accuracy: %.2f%%" % (scores[1]*100))

15/15 [==============================] - 0s 428us/step - loss: 30.3247 - accuracy: 0.6991
Accuracy: 69.91%


In [18]:
#Das Modell wird mit seinen Einstellungen gespeichert
model.save('keras_r01.keras')


In [19]:
#Das Modell wird wieder geladen
reconstructed_model = models.load_model('keras_r01.keras')


In [20]:
#Testen des geladenen Modells mit einzelnen Kommentaren
#Definiere den zu testenden Kommentar
Comment = ['good']

#Tokenize den Kommentar und sequenziere diesen
Comment = tokenizer.texts_to_sequences(Comment)
Comment = keras.preprocessing.sequence.pad_sequences(Comment, maxlen=max_comment_char_count)

#Speichere das Ergebnis des zu erwartenden Sentiments unseres Beispielsatzes
result = (reconstructed_model.predict(Comment))
#Gebe das Ergebnis aus
print(result)

#Teile die Ergebnisse in Klassen aufgrund von Erfahrungswerten des testens dieses Modells ein
if float(float(result) > 0.004):
    print("Positive Sentence")
elif float(float(result)) < 0.0041:
    print("Negative Sentence")
elif float(float(result)) > 0.005:
    print("Neutral Sentence")
else:
    print("Neutral Sentencetence")

[[0.00995107]]
Positive Sentence


In [21]:
#!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
vdAnalyzer = SentimentIntensityAnalyzer()
vdComment = "good"
vs = vdAnalyzer.polarity_scores(vdComment)
print (vs)
print("{:-<65} {}".format(vdComment, str(vs)))

#Treffen Annahmen für den zusammengesetzten Wert um positiv, negativ und neutral zu trennen
if float(vs['compound']) > 0.55:
    print("Positive Sentence")
elif float(vs['compound']) < 0.45:
    print("Negative Sentence")
else:
    print("Neutral Sentence")

{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.4404}
good------------------------------------------------------------- {'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.4404}
Negative Sentence
